MCU = STM32F401
BOOTLOADER = stm32-dfu
BOARD = BLACKPILL_STM32_F401

# Enter lower-power sleep mode when on the ChibiOS idle thread
# OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE

# Build Options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = pwm
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
DIP_SWITCH_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog
VIA_ENABLE = yes
# LTO_ENABLE = yes
