#pragma once

#include "config_common.h"

/* Device */
#define VENDOR_ID       0xDE29
#define PRODUCT_ID      0x7328
#define DEVICE_VER      0x0001
#define MANUFACTURER    Leo Deng
#define PRODUCT         Charlieplex

/* Bootmagic & DFU */
#define BOOTMAGIC_LITE_ROW 1
#define BOOTMAGIC_LITE_COLUMN 0

/* Matrix */
#define MATRIX_ROWS 4
#define MATRIX_COLS 4
#define MATRIX_ROW_PINS { F4, F5, F6, F7 }
#define MATRIX_COL_PINS { F4, F5, F6, F7 }
// #define DIODE_DIRECTION COL2ROW // COL2ROW or ROW2COL
#define UNUSED_PINS
#define DEBOUNCE 5
#define TAP_CODE_DELAY 10

/* Bluetooth */
#ifdef BLUETOOTH_ENABLE
#define ADAFRUIT_BLE_RST_PIN D4
#define ADAFRUIT_BLE_CS_PIN B4
#define ADAFRUIT_BLE_IRQ_PIN E6
#define BATTERY_LEVEL_PIN B5
#endif

/* LED Matrix */
#ifdef LED_MATRIX_ENABLE
#define LED_DRIVER_ADDR_1 0b1110100
#define LED_DRIVER_COUNT 1
#define LED_DRIVER_1_LED_TOTAL 12
#define DRIVER_LED_TOTAL (LED_DRIVER_1_LED_TOTAL)
#define BACKLIGHT_LEVELS 5
#define LED_MATRIX_KEYPRESSES
// #define LED_MATRIX_KEYRELEASES
#define LED_MATRIX_FRAMEBUFFER_EFFECTS
#define DISABLE_LED_MATRIX_TYPING_HEATMAP
#define LED_DISABLE_TIMEOUT 0
#define LED_DISABLE_AFTER_TIMEOUT 0
#define LED_DISABLE_WHEN_USB_SUSPENDED
#define LED_MATRIX_LED_PROCESS_LIMIT (DRIVER_LED_TOTAL + 4) / 5
#define LED_MATRIX_LED_FLUSH_LIMIT 16
#define LED_MATRIX_MAXIMUM_BRIGHTNESS 200
#define LED_MATRIX_STARTUP_MODE LED_MATRIX_SOLID
#define LED_MATRIX_STARTUP_VAL LED_MATRIX_MAXIMUM_BRIGHTNESS
#define LED_MATRIX_STARTUP_SPD 127
// Enable Effects
#define ENABLE_LED_MATRIX_ALPHAS_MODS // 128
#define ENABLE_LED_MATRIX_BREATHING // 158
#define ENABLE_LED_MATRIX_BAND // 100
#define ENABLE_LED_MATRIX_BAND_PINWHEEL // 338
#define ENABLE_LED_MATRIX_BAND_SPIRAL //148
#define ENABLE_LED_MATRIX_CYCLE_LEFT_RIGHT // 48
#define ENABLE_LED_MATRIX_CYCLE_UP_DOWN //48
#define ENABLE_LED_MATRIX_CYCLE_OUT_IN // 296
#define ENABLE_LED_MATRIX_DUAL_BEACON // 300
#define ENABLE_LED_MATRIX_SOLID_REACTIVE_SIMPLE // 382
#define ENABLE_LED_MATRIX_SOLID_REACTIVE_WIDE // 36
#define ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTIWIDE // 68
#define ENABLE_LED_MATRIX_SOLID_REACTIVE_CROSS // 36
#define ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTICROSS // 136
#define ENABLE_LED_MATRIX_SOLID_REACTIVE_NEXUS // 36
#define ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTINEXUS // 566
#define ENABLE_LED_MATRIX_SOLID_SPLASH // 0
#define ENABLE_LED_MATRIX_SOLID_MULTISPLASH // 0
#define ENABLE_LED_MATRIX_WAVE_LEFT_RIGHT // 60
#define ENABLE_LED_MATRIX_WAVE_UP_DOWN // 326
#endif

/* VIA */
#ifdef VIA_ENABLE
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#endif
