MCU = atmega32u4
F_CPU = 8000000
F_USB = $(F_CPU)
ARCH = AVR8
BOOTLOADER = atmel-dfu
OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT
OPT_DEFS += -DBOOTLOADER_SIZE=4096

# Build options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
BLUETOOTH_ENABLE = yes
BLUETOOTH_DRIVER = BluefruitLE
LED_MATRIX_ENABLE = yes
LED_MATRIX_DRIVER = IS31FL3731
AUDIO_ENABLE = no
CUSTOM_MATRIX = lite
VIA_ENABLE = yes
LTO_ENABLE = yes

# Custom matrix
SRC += matrix.c
