# Build Options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = software
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
OLED_DRIVER_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
VIA_ENABLE = yes
# LTO_ENABLE = yes
