MCU = at90usb646
F_CPU = 16000000
F_USB = $(F_CPU)
ARCH = AVR8
BOOTLOADER = atmel-dfu

# Build options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
RGBLIGHT_ENABLE = no

# QMK features
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = pwm
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
AUDIO_ENABLE = yes
# BLUETOOTH_ENABLE = no
# BLUETOOTH = AdafruitBLE
NKRO_ENABLE = no
DIP_SWITCH_ENABLE = yes
ENCODER_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick
JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog
# DIGITIZER_ENABLE = yes
PS2_MOUSE_ENABLE = yes
PS2_USE_USART = yes
# VIA_ENABLE = yes
