MCU = atmega32u4
F_CPU = 8000000
F_USB = $(F_CPU)
ARCH = AVR8
BOOTLOADER = atmel-dfu
OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT
OPT_DEFS += -DBOOTLOADER_SIZE=4096

# Build options
BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BLUETOOTH_ENABLE = yes
BLUETOOTH_DRIVER = BluefruitLE
CUSTOM_MATRIX = lite
SRC += matrix.c

#####################
# Optional features #
#####################

# OLED_ENABLE = yes
# OLED_DRIVER = SSD1306
BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = pwm
# RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
# AUDIO_ENABLE = yes
# MIDI_ENABLE = yes
# DIP_SWITCH_ENABLE = yes
ENCODER_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes
