MCU = STM32F103
BOARD = STM32_F103_STM32DUINO

OPT_DEFS += -DBOOTLOADER_STM32DUINO
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
MCU_LDSCRIPT = STM32F103x6_stm32duino_bootloader
BOOTLOADER_TYPE = stm32duino
DFU_ARGS = -d 1EAF:0003 -a 2 -R
DFU_SUFFIX_ARGS = -v 1EAF -p 0003

MOUSEKEY_ENABLE = no
VIA_ENABLE = no
LTO_ENABLE = yes
EEPROM_DRIVER = transient
