MCU = atmega32u4
F_CPU = 16000000
F_USB = $(F_CPU)
ARCH = AVR8
BOOTLOADER = atmel-dfu
OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT
OPT_DEFS += -DBOOTLOADER_SIZE=4096

# Build Options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
PS2_MOUSE_ENABLE = yes
PS2_USE_USART = yes
AUDIO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
VIA_ENABLE = no
# DIP_SWITCH_ENABLE = yes
# BLUETOOTH_ENABLE = no
# BLUETOOTH = AdafruitBLE
MIDI_ENABLE = yes
LTO_ENABLE = yes
