MCU = atmega32u4
BOOTLOADER = atmel-dfu

# Build Options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
PS2_MOUSE_ENABLE = yes
PS2_USE_USART = yes
AUDIO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
VIA_ENABLE = no
# DIP_SWITCH_ENABLE = yes
# BLUETOOTH_ENABLE = no
# BLUETOOTH = AdafruitBLE
MIDI_ENABLE = yes
LTO_ENABLE = yes
