MCU = STM32F401
BOOTLOADER = stm32-dfu
BOARD = BLACKPILL_STM32_F401

# Build Options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
AUDIO_ENABLE = no
OLED_DRIVER_ENABLE = no
DIP_SWITCH_ENABLE = yes
LTO_ENABLE = no
VIA_ENABLE = yes
CUSTOM_MATRIX = lite

SRC += analog.c matrix.c
