MCU = STM32F303
BOARD = QMK_PROTON_C
BOOTLOADER = stm32-dfu

# Build Options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = software
RGBLIGHT_ENABLE = no
VIA_ENABLE = yes
