MCU = STM32F103
BOARD = STM32_F103_STM32DUINO

OPT_DEFS += -DBOOTLOADER_STM32DUINO
# OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
MCU_LDSCRIPT = STM32F103x6_stm32duino_bootloader
BOOTLOADER_TYPE = stm32duino
DFU_ARGS = -d 1EAF:0003 -a 2 -R
DFU_SUFFIX_ARGS = -v 1EAF -p 0003

# Build Options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
RGB_MATRIX_ENABLE = no
JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog
VIA_ENABLE = no
LTO_ENABLE = no
# EEPROM_DRIVER = transient
EEPROM_DRIVER = vendor
